REM   Script: Activity7
REM   Activity7 SQL

SELECT SUM(PURCHASE_AMOUNT) AS TOTAL_PURCHASE_AMT FROM ORDERS;

SELECT AVG(PURCHASE_AMOUNT) AS AVG_PURCHASE_AMT FROM ORDERS;

SELECT ROUND(AVG(PURCHASE_AMOUNT),0) AS AVG_PURCHASE_AMT FROM ORDERS;

SELECT MAX(PURCHASE_AMOUNT) AS MAX_PURCHASE_AMT FROM ORDERS;

SELECT MIN(PURCHASE_AMOUNT) AS MIN_PURCHASE_AMT FROM ORDERS;

SELECT COUNT(DISTINCT SALESMAN_ID) AS NO_SALESMAN FROM ORDERS;

