REM   Script: Activity8
REM   Activity8 SQL


SELECT * FROM ORDERS;

SELECT CUSTOMER_ID, MAX(PURCHASE_AMOUNT) AS MAX_AMT FROM ORDERS GROUP BY CUSTOMER_ID;

SELECT SALESMAN_ID, ORDER_DATE, MAX(PURCHASE_AMOUNT) AS MAX_AMT FROM ORDERS GROUP BY SALESMAN_ID,ORDER_DATE HAVING ORDER_DATE=To_DATE('2012/08/17', 'YYYY/MM/DD');

SELECT CUSTOMER_ID, ORDER_DATE, MAX(PURCHASE_AMOUNT) MAX_AMT FROM ORDERS GROUP BY CUSTOMER_ID,ORDER_DATE HAVING MAX(PURCHASE_AMOUNT) IN (2030, 3450, 5760, 6000);

